PATH="$HOME/.local/bin:$PATH"
export PATH

# Bash initialization for interactive non-login shells and
# for remote shells (info "(bash) Bash Startup Files").

# Export 'SHELL' to child processes.  Programs such as 'screen'
# honor it and otherwise use /bin/sh.
export SHELL

if [[ $- != *i* ]]
then
    # We are being invoked from a non-interactive shell.  If this
    # is an SSH session (as in "ssh host command"), source
    # /etc/profile so we get PATH and other essential variables.
    [[ -n "$SSH_CLIENT" ]] && source /etc/profile

    # Don't do anything else.
    return
fi

# Adjust the prompt depending on whether we're in 'guix environment'.
if [ -n "$GUIX_ENVIRONMENT" ]
then
    PS1='\u@\h \w [env]\$ '
else
    PS1='\u@\h \w\$ '
fi

HISTSIZE=4096
HISTFILE=$HOME/.history
COLORTERM=24bit
export HISTSIZE HISTFILE COLORTERM

alias ls='ls -p --color=auto'
alias ll='ls -l'
alias la='ls -al'
alias grep='grep --color=auto'
alias em='emacs -nw'
alias emd='emacs --daemon'
alias ec='emacsclient -nw -c -t'
alias clear='printf "\033[H\033[2J"'

bind -m '^L'=^U\ clear'^J^Y'

window_restore() {
	wlr-randr --output Virtual-1 --mode 1440x900
}

window_maximize() {
	wlr-randr --output Virtual-1 --mode 1920x1080
}
